////Generated by Prefab3D 2.146, Thu Oct 10 17:13:33 GMT+0200 2013. www.closier.nl/prefab
package net.psykosoft.psykopaint2.home.views.home.atelier.data {

	import away3d.core.base.Geometry;

	public class Walls_editmaterial1Data {

		[Embed(source="../../../../../../../../../assets/embedded/away3d/atelier/asd/Walls_editmaterial1Data.asd", mimeType="application/octet-stream")]
		private var Walls_editmaterial1DataASD:Class;

		public function get geometryData():Geometry
		{
			return ASDReader.decodeGeometry(new Walls_editmaterial1DataASD());
		}

	}
}