//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
///
// Parameters:
//
//   Texture2D linearSampler+bottom;
//   Texture2D linearSampler+top;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   linearSampler+top    s0       1
//   linearSampler+bottom s1       1
//

    ps_3_0
    def c0, 1, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xy
    dcl_2d s0
    dcl_2d s1
    texld r0, v0, s0
    add r1.x, -r0.w, c0.x
    texld r2, v1, s1
    mad oC0.w, r2.w, r1.x, r0.w
    add r0.xyz, r0, r2
    mad oC0.xyz, r2.w, -r0.w, r0

// approximately 6 instruction slots used (2 texture, 4 arithmetic)
