//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
///
// Parameters:
//
//   Texture2D linearSampler+pigmentField;
//   Texture2D linearSampler+velocityField;
//
//
// Registers:
//
//   Name                        Reg   Size
//   --------------------------- ----- ----
//   linearSampler+velocityField s0       1
//   linearSampler+pigmentField  s1       1
//

    ps_3_0
    def c0, -0.5, 0, -0, 1
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xy
    dcl_texcoord2 v2.xy
    dcl_texcoord3 v3.xy
    dcl_texcoord4 v4.xy
    dcl_2d s0
    dcl_2d s1
    texld r0, v1, s1
    texld r1, v0, s0
    add r0.yz, r1.xxyw, c0.x
    add r0.yz, r0, r0
    mul r1.y, r0.x, r0.y
    texld r2, v3, s1
    mul r1.w, r0.z, r2.x
    max r2.yw, -r1, c0.z
    texld r1, v2, s1
    texld r3, v2, s0
    add r0.x, r3.x, c0.x
    add r0.x, r0.x, r0.x
    mul r1.x, r1.x, r0.x
    texld r3, v4, s1
    texld r4, v4, s0
    add r0.w, r4.y, c0.x
    add r0.w, r0.w, r0.w
    mul r1.z, r3.x, r0.w
    max r2.xz, r1, c0.y
    texld r1, v0, s1
    mul r3.yw, r0.xxzw, r1.x
    max r4.yw, -r3, c0.z
    mul r0.xy, r0.yzzw, r1.x
    max r4.xz, r0.xyyw, c0.y
    add r0, r2, -r4
    dp4 r0.x, r0, c0.w
    add oC0.x, r0.x, r1.x
    mov oC0.yzw, r1

// approximately 28 instruction slots used (8 texture, 20 arithmetic)
