//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
///
// Parameters:
//
//   Texture2D linearSampler+field;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   linearSampler+field s0       1
//

    ps_3_0
    def c0, 0.100000001, 2, 0, 0
    dcl_texcoord v0.xy
    dcl_texcoord1 v1.xy
    dcl_texcoord2 v2.xy
    dcl_texcoord3 v3.xy
    dcl_texcoord4 v4.xy
    dcl_texcoord5 v5.xy
    dcl_texcoord6 v6.xy
    dcl_2d s0
    texld r0, v2, s0
    texld r1, v1, s0
    texld r2, v0, s0
    add r0.x, -r1.x, r2.x
    add r0.x, r2.y, r0.x
    add r0.x, -r0.y, r0.x
    mul r0.y, r0.x, c0.x
    mad oC0.z, -r0.y, c0.y, r2.z
    mov oC0.w, r2.w
    mad r0.xy, r0.x, -c0.x, r2
    texld r1, v3, s0
    add r0.z, -r0.x, r1.x
    add r0.z, r1.y, r0.z
    texld r1, v4, s0
    add r1.x, r0.z, -r1.y
    texld r2, v6, s0
    texld r3, v5, s0
    add r0.z, -r2.x, r3.x
    add r0.z, r3.y, r0.z
    add r1.y, -r0.y, r0.z
    mad oC0.xy, r1, c0.x, r0

// approximately 21 instruction slots used (7 texture, 14 arithmetic)
