//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
///
// Parameters:
//
//   float density;
//   float densityOverStainingPower;
//   float granulation;
//   Texture2D linearSampler+normalHeightMap;
//   Texture2D linearSampler+pigmentField;
//
//
// Registers:
//
//   Name                          Reg   Size
//   ----------------------------- ----- ----
//   granulation                   c0       1
//   density                       c1       1
//   densityOverStainingPower      c2       1
//   linearSampler+pigmentField    s0       1
//   linearSampler+normalHeightMap s1       1
//

    ps_3_0
    def c3, 1, -1, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    texld r0, v0, s1
    mov r0.x, c3.x
    mad r0.y, r0.w, -c0.x, r0.x
    add r0.z, r0.w, c3.y
    mad r0.x, r0.z, c0.x, r0.x
    texld r1, v0, s0
    mul r0.xy, r0, r1.yxzw
    mul r0.y, r0.y, c1.x
    mad r0.x, r0.x, c2.x, -r0.y
    add oC0.x, r0.x, r1.x
    add oC0.y, -r0.x, r1.y
    mov oC0.zw, r1

// approximately 12 instruction slots used (2 texture, 10 arithmetic)
